apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
          ports:
          - containerPort: 9200
          - containerPort: 9300
          env:
          - name: discovery.type
            value: "single-node"
          - name: node.name
            value: es-master-node      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.12.0
          ports:
          - containerPort: 5601          
---

kind: Service
apiVersion: v1
metadata:
  name: kibana-svc
  labels:
    name: kibana-svc
spec:
  selector:
    app: kibana
  ports:
  - port: 5601 
    targetPort: 5601
  type: LoadBalancer

---
# 用elasticsearch做svc的名字，kibana可以直接默认访问不然需配置一下kibana的访问地址
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200 
    targetPort: 9200
  type: LoadBalancer
