version: "3"
services:
  jobmanager:
    image: flink:1.12.4-scala_2.11-java8
    container_name: flink-jobmanager
    ports:
      - "127.0.0.1:38081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.12.4-scala_2.11-java8
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4