# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

xpack.monitoring.ui.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true