version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.13.4
    container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - "discovery.type=single-node"
      - "node.name=es-node"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3000M
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options

  kibana:
    image: kibana:7.13.4
    container_name: kibana
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 768M
    environment:
      - "xpack.monitoring.ui.container.elasticsearch.enabled"
    # volumes:
      # - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
       