version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.3.0
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "127.0.0.1:18081:8080"
      - "127.0.0.1:6650:6650"
    restart: unless-stopped
    volumes:
      - "./data/pulsar:/pulsar/data"
  dashboard:
    image: leriou/pulsar-manager:latest
    ports:
      - 127.0.0.1:9527:9527
      - 127.0.0.1:7750:7750
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties