version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: "pulsar"
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "127.0.0.1:18081:8080"
      - "127.0.0.1:6650:6650"
    restart: unless-stopped
    volumes:
      - "./data/pulsar:/pulsar/data"
  dashboard:
    image: apachepulsar/pulsar-manager:latest
    container_name: "pulsar-manager"
    ports:
      - "127.0.0.1:9527:9527"
      - "127.0.0.1:7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    volumes:
      - "./data/manager:/data"
    environment:
      REDIRECT_HOST: "http://127.0.0.1"
      REDIRECT_PORT: "9527"
      DRIVER_CLASS_NAME: "org.postgresql.Driver"
      URL: "jdbc:postgresql://pgsql:5432/pulsar_manager"
      USERNAME: "pguser"
      PASSWORD: "123456"
      LOG_LEVEL: "DEBUG"