version: '3.1'
services:
  post:
    image: postgres:11.1-alpine
    container_name: postgresql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=pgroot
      - POSTGRES_PASSWORD=123456
      - PGDATA=/data
    volumes:
      - ./data:/data