apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyter/tensorflow-notebook:latest
          ports:
          - containerPort: 8888
---

apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
  labels:
    name: jupyter-svc
spec:
  selector:
    app: jupyter
  ports:
  - port: 8888 
    targetPort: 8888
  type: LoadBalancer
