version: "3"
services: 
    mysql:
        image: mysql:8.0.25
        command: --default-authentication-plugin=mysql_native_password
        environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=wordpress
        ports:
        - "127.0.0.1:3306:3306"
        volumes:
        - ./data/mysql:/var/lib/mysql
        container_name: mysql