version: '3'
services:
  master: 
    image: harisekhon/hbase:2.0
    container_name: master
    ports:
      - "19010:22"
      - "50070:50070"
      - "8088:8088"
      - "16010:16010"
  slave1: 
    image: harisekhon/hbase:2.0
    container_name: slave1
    depends_on:
      - master
    ports:
      - "19011:22"
    restart: always
  slave2: 
    image: harisekhon/hbase:2.0
    container_name: slave2
    depends_on:
      - slave1
    ports:
      - "19012:22"

