version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.6.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
      - net-es

  kibana:
    image: kibana:6.6.0
    container_name: kibana
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - net-es
      
networks:
  net-es:
