version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.1.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "node.name=es-node-1"
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
      - net-es

  kibana:
    image: kibana:7.1.0
    container_name: kibana
    environment:
      - "xpack.monitoring.ui.container.elasticsearch.enabled"
    ports:
      - "5601:5601"
    networks:
      - net-es
      
networks:
  net-es:
