mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=wordpress
    ports:
     - "127.0.0.1:3306:3306"
    volumes:
     - ./data/mysql:/var/lib/mysql
    container_name: mysql
web:
    image: wordpress:5.0.3
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=123456
    ports:
     - "127.0.0.1:8077:80"
    working_dir: /var/www/html
    volumes:
     - ./data/html:/var/www/html
    container_name: wordpress
