version: "3"
services:
  portainerss:
    image: portainer/portainer:1.20.2
    container_name: portainer
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # 必须要有
      - "./data:/data"                     # 非必须


