version: "3"
services: 
    mariadb:
        image: mariadb:10.6.2
        environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=wordpress
        ports:
        - "127.0.0.1:3306:3306"
        volumes:
        - ./data/mysql:/var/lib/mysql
        container_name: mariadb
        
    web:
        image: wordpress:latest
        links:
        - mariadb
        environment:
        - WORDPRESS_DB_PASSWORD=123456
        ports:
        - "127.0.0.1:8077:80"
        working_dir: /var/www/html
        volumes:
        - ./data/html:/var/www/html
        container_name: wordpress

       
