apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeppelin
spec:
  selector:
    matchLabels:
      app: zeppelin
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: apache/zeppelin:0.9.0
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: zeppelin-svc
  labels:
    name: zeppelin-svc
spec:
  selector:
    app: zeppelin
  ports:
  - port: 8080 
    targetPort: 8080
  type: LoadBalancer
