version: "3"
services:
  pulsar:
    image: apachepulsar/pulsar:2.3.0
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./data:/pulsar/data 
    command: bin/pulsar standalone